# Generated by Django 3.2.4 on 2021-06-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imtahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tarix', models.DateTimeField()),
            ],
            options={
                'ordering': ('cdate',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Neticeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload')),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('imtahan_id', models.ManyToManyField(blank=True, to='core.Imtahan')),
            ],
            options={
                'ordering': ('cdate',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamCorrect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload')),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('imtahan_id', models.ManyToManyField(blank=True, to='core.Imtahan')),
            ],
            options={
                'ordering': ('cdate',),
                'abstract': False,
            },
        ),
    ]
