# Generated by Django 3.2.4 on 2021-06-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210618_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('log', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('cdate',),
                'abstract': False,
            },
        ),
    ]
